### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-compare#23]
Current dist version mismatches to npm: https://github.com/mapbox/mapbox-gl-compare/commit/450c68eddcea21e32d5161b4e4eec98493e1aa1d

And examples in README too. Thanks.

**Comment by andrewharvey** [comment]
The examples in README etc. represent what's in the `master` branch, not necessarily the latest release, for docs for the latest release you can check out the release tags https://github.com/mapbox/mapbox-gl-compare/tree/0.2.1.

When a new release is done that will eventually be pushed to npm. If you want to help out with a release the instructions are at https://github.com/mapbox/mapbox-gl-compare/tree/0.2.1#deploying you could submit this as a PR, I'd be happy to help review that, then someone at Mapbox would be able to complete the final steps pushing to npm and tagging. Thanks!

**Comment by andrewharvey** [comment]
0.3.0 was released and published to npm
