### ISSUE TITLE
Add a white background color to the pending map container

### ISSUE THREAD

**Issue by dereklieu** [mapbox/mapbox-gl-compare#24]
When comparing two map styles, if the pending style has spots with no fill polygons (ie transparent areas) it appears as if this module is broken.

![publish](https://user-images.githubusercontent.com/1590802/66349056-dbeafa80-e90c-11e9-96b4-3f593555199b.gif)

In this example, I've taken a simple map style in Studio and removed a land layer. 

To address this, I recommend adding a `background-color: white` style to the container of the pending map.

![publish-2](https://user-images.githubusercontent.com/1590802/66349183-253b4a00-e90d-11e9-8945-7d3cbad3939a.gif)

**Comment by samanpwbb** [comment]
👍, but I suggest we user a css class so the background element is themeable, we'll want a 🏁 pattern in Studio.
