### ISSUE TITLE
v0.3.0 is not available via CDN

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-compare#30]
`v0.3.0` is not available via Mapbox CDN, [this example](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-compare/) still uses `v0.1.0`

https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-compare/v0.3.0/mapbox-gl-compare.js
https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-compare/v0.3.0/mapbox-gl-compare.css

**Comment by Agos88** [comment]
I'm still using the `v0.1.0` and it doesn't work sometimes:

`TypeError: mapboxgl.Compare is not a constructor`

Is there the possibility to use the `v0.3.0`?

**Comment by andrewharvey** [comment]
@riastrad @elifitch could the Mapbox CDN be updated with 0.2.0, 0.3.0 and 0.4.0?
