### ISSUE TITLE
compare on mousemove option

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-compare#4]
it would be nice to support an option to compare on mouse move, opposed to dragging the slider.

I've put together a rather crude sketch of this at https://github.com/andrewharvey/mapbox-gl-compare/tree/follow-cursor

In my sketch it's either one approach or the other but it should probably support a hybrid method for devices which have both a mouse and touchscreen, as touchscreen devices would need the slider to drag for a better UX.

**Comment by tristen** [comment]
Added a PR for this here: https://github.com/mapbox/mapbox-gl-compare/pull/6. Implementation is simpler with a hybrid approach as you don't need to disable the interactions for touch with this option enabled. If the user doesn't wish to display the control UI they can hide it using CSS.

**Comment by tristen** [comment]
^
