### ISSUE TITLE
Fails import into sveltejs application

### ISSUE THREAD

**Issue by AntoniBCN** [mapbox/mapbox-gl-compare#44]
Trying to import 'mapbox-gl-compare' to an svelte app, I get the following error "Could not find a declaration file for module 'mapbox-gl-compare' ...." (See attached image).

What is wrong? 

I've tried the command npm i --save-dev @types/mapbox-gl-compare but it still doesn't work.

Thanks in advance.
![vs2](https://user-images.githubusercontent.com/26866763/145425637-900f89b3-a0a6-4f69-8c05-e1512164302d.png)

**Comment by tristen** [comment]
Does it fail or just warn? This package does not currently have a declaration file. I would suggest following the second suggestion of adding a new declaration file containing `declare module 'mapbox-gl-compare';` or contributing to the https://github.com/DefinitelyTyped/DefinitelyTyped project to add a `@types/mapbox-gl-compare` package.

**Comment by AntoniBCN** [comment]
Hi, @tristen  It fails but, as you said, I applied the second suggestion and three white dots disappear.
